# Generated by Django 4.2.3 on 2023-08-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcard',
            name='price',
            field=models.CharField(default='$1', max_length=200),
        ),
        migrations.AlterField(
            model_name='createcard',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createcard',
            name='img_url',
            field=models.TextField(),
        ),
    ]
